const genres = {
    anime: [
        { title: "Action", value: "1" },
        { title: "Adventure", value: "2" },
        { title: "Cars", value: "3" },
        { title: "Comedy", value: "4" },
        { title: "Avante Garde", value: "5" },
        { title: "Demons", value: "6" },
        { title: "Mystery", value: "7" },
        { title: "Drama", value: "8" },
        { title: "Ecchi", value: "9" },
        { title: "Fantasy", value: "10" },
        { title: "Game", value: "11" },
        { title: "Hentai", value: "12" },
        { title: "Historical", value: "13" },
        { title: "Horror", value: "14" },
        { title: "Kids", value: "15" },
        { title: "Martial Arts", value: "17" },
        { title: "Mecha", value: "18" },
        { title: "Music", value: "19" },
        { title: "Parody", value: "20" },
        { title: "Samurai", value: "21" },
        { title: "Romance", value: "22" },
        { title: "School", value: "23" },
        { title: "Sci Fi", value: "24" },
        { title: "Shoujo", value: "25" },
        { title: "Girls Love", value: "26" },
        { title: "Shounen", value: "27" },
        { title: "Boys Love", value: "28" },
        { title: "Space", value: "29" },
        { title: "Sports", value: "30" },
        { title: "Super Power", value: "31" },
        { title: "Vampire", value: "32" },
        { title: "Harem", value: "35" },
        { title: "Slice Of Life", value: "36" },
        { title: "Supernatural", value: "37" },
        { title: "Military", value: "38" },
        { title: "Police", value: "39" },
        { title: "Psychological", value: "40" },
        { title: "Suspense", value: "41" },
        { title: "Seinen", value: "42" },
        { title: "Josei", value: "43" },
        { title: "Award Winning", value: "46" },
        { title: "Gourmet", value: "47" },
        { title: "Work Life", value: "48" },
        { title: "Erotica", value: "49" }
    ],
    manga: [
        { title: "Action", value: "1" },
        { title: "Adventure", value: "2" },
        { title: "Cars", value: "3" },
        { title: "Comedy", value: "4" },
        { title: "Avante Garde", value: "5" },
        { title: "Demons", value: "6" },
        { title: "Mystery", value: "7" },
        { title: "Drama", value: "8" },
        { title: "Ecchi", value: "9" },
        { title: "Fantasy", value: "10" },
        { title: "Game", value: "11" },
        { title: "Hentai", value: "12" },
        { title: "Historical", value: "13" },
        { title: "Horror", value: "14" },
        { title: "Kids", value: "15" },
        { title: "Martial Arts", value: "17" },
        { title: "Mecha", value: "18" },
        { title: "Music", value: "19" },
        { title: "Parody", value: "20" },
        { title: "Samurai", value: "21" },
        { title: "Romance", value: "22" },
        { title: "School", value: "23" },
        { title: "Sci Fi", value: "24" },
        { title: "Shoujo", value: "25" },
        { title: "Girls Love", value: "26" },
        { title: "Shounen", value: "27" },
        { title: "Boys Love", value: "28" },
        { title: "Space", value: "29" },
        { title: "Sports", value: "30" },
        { title: "Super Power", value: "31" },
        { title: "Vampire", value: "32" },
        { title: "Harem", value: "35" },
        { title: "Slice Of Life", value: "36" },
        { title: "Supernatural", value: "37" },
        { title: "Military", value: "38" },
        { title: "Police", value: "39" },
        { title: "Psychological", value: "40" },
        { title: "Seinen", value: "41" },
        { title: "Josei", value: "42" },
        { title: "Doujinshi", value: "43" },
        { title: "Gender Bender", value: "44" },
        { title: "Suspense", value: "45" },
        { title: "Award Winning", value: "46" },
        { title: "Gourmet", value: "47" },
        { title: "Work Life", value: "48" },
        { title: "Erotica", value: "49" }
    ]
}

export default genres;